# Logiciels requis pour utiliser et travailler sur les documents du cours MethNum
name: npac-ac-jupyterlite

channels:
- conda-forge
- https://repo.mamba.pm/emscripten-forge

dependencies:
- xeus-python 
- pandas#==0.24.2
- numpy#==1.16.2
- matplotlib#==3.0.3
- scipy#==1.2.1
- pillow#==6.0.0
- jupytext
- ipywidgets
- ipympl
- astropy<6.0
- sympy
- pip:
  - ipyturtle3
  - astropy['all']

